### ISSUE TITLE
Wrong addressing when mentioning a user

### ISSUE THREAD

**Issue by mdosch** [mdom/txtnish#11]
I have the following users in my following list:

```
grep kas ~/.config/txtnish/following 
kas https://enotty.dk/twtxt.txt
kasdk https://enotty.dk/kasdk.txt
```
When I mentioned `@kasdk` the following went into my twtxt file:

```
@<kas https://enotty.dk/twtxt.txt>dk ...remaining tweet...
```

**Comment by mdom** [comment]
Yeah, I can confirm the issue, the culprit is probably https://github.com/mdom/txtnish/blob/4a0f81e3e862cd5bd3f2e5d22e80b6a023af2d57/bin/txtnish#L617

**Comment by mdom** [comment]
I just pushed a fix for this problem. It would be great if you can test if it works for you now!

**Comment by mdosch** [comment]
It worked well now. THX!
