### ISSUE TITLE
@ in URLs are recognized as mentions

### ISSUE THREAD

**Issue by Lucidiot** [mdom/txtnish#12]
I tried tweeting a Mastodon toot URL, which has an `@` in it. As it was a link with my own nickname in it, it had `@lucidiot`, which was understood as being myself and apparently removed: `txtnish tweet http://something/@lucidiot/aaaa` sends a toot with only `/aaaa` in it.

**Comment by mdom** [comment]
This seems to be general problem with the way we handle nickname expansion. Does anybody have any idea how txtnish or other twtxt clients should handle that case without missing mentions in parens or with punctuation marks?

**Comment by VonKavalier** [comment]
Maybe we could prevent nick handling when the @ is directly next to a character ?

Like :
- `@testnickname hello` -> :ok: 
- `https://url.com/@testnickname/test` -> :negative_squared_cross_mark: 
- `some text @testnickname some text` -> :ok: 
- `some text badwrittne@testnickname some text` -> :negative_squared_cross_mark: 

What do you think ?

**Comment by mdom** [comment]
I'm not sure about a nick in parens like _(@testnickname)_? Should i prevent expansaion in that case? But maybe it's preferable to not mangle urls and emails than to handle every corner case. I implement the idea by @VonKavalier and we see if anybody complains.

**Comment by VonKavalier** [comment]
Or if we can see that only urls and email addresses are the problem, a regex could potentially be cleaner :thinking:

**Comment by mdom** [comment]
Let's try the easier approach before we match urls and email with awks regex engine... :)
