### ISSUE TITLE
macOS awk can't handle -vvar="$var"

### ISSUE THREAD

**Issue by rnkn** [mdom/txtnish#17]
Hello,

Thanks for making txtnish. It's really cool. #POSIX4LIFE

I ran into a tiny hurdle on macOS... When calling `format_msg()` via `txtnish timeline` awk aborts with:
~~~sh
awk: invalid -v option
~~~
which can be reproduced with:
~~~sh
$ echo hello | awk -vvar=" world" '{ print $0 var }'
awk: invalid -v option
$ echo hello | awk -v var=" world" '{ print $0 var }'
hello world
~~~
I would have just submitted the patch:
~~~diff
 format_msg () {
 
 	export color_nick color_time color_hashtag color_mention use_color formatter
-	$awk -vtheme="$1" '
+	$awk -v theme="$1" '
 		function colors_to_escape ( color,  fgc, bgc, n, c, attr ) {
 			n = split(color,c,/ /)
 			for (i=1; i<=n; i++ ) {
~~~
but this doesn't appear to cut it, as then `txtnish timeline` just returns a blank timeline.

The solution/workaround I've found is just to set `awk=gawk`.
(but then wonder if it's still POSIX...).

This doesn't seem to be a problem with a newer awk (OpenBSD).

Thanks for your time :)

**Comment by mdom** [comment]
Thanks for sending the patch. Even if it did not work for you an MacOS it seems to be a good idea to seperate the option from the assignment by a space.

I'll try to get access to a MacOS machine to test it there. Which version of MacOS are you using? And do you know what version of awk it's using?

Cheers, Mario

**Comment by rnkn** [comment]
~~~
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G14042
$ awk --version
awk version 20070501
~~~
I am a holdout against Apple's ideas of progress, but I see from https://opensource.apple.com/source/awk/awk-27.40.1/src/main.c.auto.html that they upgraded awk to `version 20200816` in macOS 11.

I'll have a poke around and see if I can narrow down what's tripping up the timeline output.

**Comment by mdom** [comment]
Just reopen the issue if you have new information.
