### ISSUE TITLE
incorrect import of twtxt config's disclose_identity

### ISSUE THREAD

**Issue by JinnCirce** [mdom/txtnish#19]
it imports it as "False" instead of "0" which then causes further parsing to break when checking the value of that field
should be trivial fix to just `sed 's/[fF]alse/0/;s/[tTrue]/1/'`

**Comment by mdom** [comment]
Yeah, that's probably a bug, but to be honest i'm a bit reluctant to change anything in the code. I haven't used txtnish in almost a year and don't participate in anything twtxt related. I think it's probably the right time to archive this project for good. Sorry. Maybe you could fix that in a fork? Cheers, Mario
