### ISSUE TITLE
[suggestion] import twtxt's followed users, not only config?

### ISSUE THREAD

**Issue by JinnCirce** [mdom/txtnish#20]
I myself imported the list with
```sh
grep -A99999999 "^\[following\]$" ~/.config/twtxt/config|
tail -n +2|
sed 's/ =//'|
grep -v "^[[:blank:]]*$" |
tee ~/.config/txtnish/following
```
which might be a bit brittle, given that if there is anything after the following section it would grab all that too (plus grep -A), but something that imports the lines during quicksetup would be great...

**Comment by mdom** [comment]
Closed pre-archivcal. Sorry.
