### ISSUE TITLE
Raw timeline

### ISSUE THREAD

**Issue by durcheinandr** [mdom/txtnish#4]
Is it possible to implement an option for viewing timeline without formatting and every tweet in its own line with Timestamp, Username and Tweet? This will be useful (for me) to automatically generate a raw timeline, which is easier to convert to html or markdown. My Goal is showing my twtxt-timeline in a browser rather than using SSH on my mobile phone.

Example:
```
Timestamp\tUsername\tTweet
2017-03-06T21:49:44.000000Z\tmdom\t@<tux0r https://rosaelefanten.org/twtxt.txt> Welcome to twtxt!
```

**Comment by mdom** [comment]
The easiest solution is to just print out the internal timeline before it's formatted. Can you check if the option -R in a15faa5fe65281bdd10ecd26a50b8811f68ecf4f does the trick for you? I should probably add a header to the output as it's just the middle of an internal pipeline and prone to change.

**Comment by durcheinandr** [comment]
Works perfect. Thanks for adding the -R option.
